### ISSUE TITLE
Port `app-click` to use musl

### ISSUE THREAD

**Issue by StefanJum** [unikraft/app-click#3]
Port `app-click` to use [musl](https://github.com/unikraft/lib-musl), the new supported unikraft glibc.

You should create the `Makefile`  and `Makefile.uk` files.
You can find more information on this on [the Unikraft website](https://unikraft.org/docs/usage/make_build/#extending-the-build).
You can find a list of the external libraries the application depends on in the [`kraft.yaml` file, under the `libraries:` section](https://github.com/unikraft/app-click/blob/staging/kraft.yaml#L11-L18).
You will need to replace the `newlib` dependency with `musl`.

Hackathon points: 40

**Comment by adamkapetis** [comment]
working on it
